- name: "Install required packages"
  apt:
    name: "{{ item }}"
    state: present
#    update_cache: true
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: "Add Docker repo key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Ubuntu Docker repository"
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: "Install packages"
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: Add user Vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: "Start Docker Service"
  service:
    name: docker
    state: started
    enabled: yes

