---
- name: Deploy Docker.
  hosts: all
  become: yes
  roles:
    - docker

- name: Deploy Node-Exporter.
  hosts: all
  become: yes
  roles:
    - node-exporter

- name: Run docker-compose.
  hosts: all
  tasks:
    - name: Run script 
      script: /vagrant/.ansible/compose.sh
